apiVersion: apps/v1
kind: Deployment
metadata:
  name: guna-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guna
  template:
    metadata:
      labels:
        app: guna
    spec:
      containers:
      - name: guna-container
        image: mbasav/guna-app:latest
        ports:
        - containerPort: 80
