apiVersion: apps/v2
kind: Deployment
metadata:
  name: tic-tac-toe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - name: tic-tac-toe
        image: 911777263281.dkr.ecr.ap-south-1.amazonaws.com/tic-tac-toe:v2
        ports:
        - containerPort: 80